# Generated by Django 4.2.4 on 2023-09-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('standards', 'Standard'), ('sport', 'Sport'), ('sport-touring', 'Sport Touring'), ('touring', 'Touring'), ('cruiser', 'Cruiser'), ('off-road', 'Off Road')], default='standards', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='engine_cc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
